import PDFDocument from "pdfkit";
import nodemailer from "nodemailer";
import dotenv from "dotenv";

dotenv.config();

const transporter = nodemailer.createTransport({
  service: process.env.EMAIL_SERVICE,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASSWORD,
  },
});

// Generate PDF buffer from guest data
const generatePDF = (wedding, guests, stats) => {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ size: "A4", layout: "landscape", margin: 30 });
    const buffers = [];

    doc.on("data", (chunk) => buffers.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    // Header
    doc.fontSize(18).font("Helvetica-Bold").text("Digital Newta Manager - Wedding Summary", { align: "center" });
    doc.moveDown(0.3);
    doc.fontSize(12).font("Helvetica").text(`${wedding.brideName} & ${wedding.groomName}`, { align: "center" });
    doc.fontSize(10).text(`Date: ${new Date(wedding.date).toLocaleDateString("en-IN")}  |  Venue: ${wedding.venue}`, { align: "center" });
    doc.moveDown(0.5);

    // Stats
    doc.fontSize(10).font("Helvetica-Bold");
    doc.text(`Total Guests: ${guests.length}  |  Attended: ${stats.attended}  |  Total Amount: ₹${stats.totalAmount.toLocaleString()}`);
    doc.text(`Cash: ${stats.cashCount}  |  UPI: ${stats.upiCount}  |  Envelope: ${stats.envelopeCount}`);
    doc.moveDown(0.5);

    // Table header
    const headers = ["#", "Name", "Village", "Mobile", "Tag", "Priority", "Attended", "Amount", "Payment", "Added"];
    const colWidths = [25, 100, 80, 75, 60, 45, 55, 55, 60, 50];
    let y = doc.y;

    doc.fontSize(8).font("Helvetica-Bold");
    let x = 30;
    headers.forEach((h, i) => { doc.text(h, x, y, { width: colWidths[i] }); x += colWidths[i]; });
    y += 15;
    doc.moveTo(30, y).lineTo(770, y).stroke();
    y += 5;

    // Table rows
    doc.font("Helvetica").fontSize(7);
    guests.forEach((g, idx) => {
      if (y > 540) { doc.addPage(); y = 30; }
      x = 30;
      const row = [
        idx + 1, g.name, g.village, g.mobileNumber || "—", g.tag || "—",
        g.priority || "—", g.attended ? "Yes" : "No", `₹${g.amount || 0}`,
        g.paymentType || "—", g.addedOn || "—",
      ];
      row.forEach((cell, i) => { doc.text(String(cell), x, y, { width: colWidths[i] }); x += colWidths[i]; });
      y += 12;
    });

    // Footer
    doc.moveDown(1);
    doc.fontSize(8).fillColor("gray").text("Generated by DigitalNewtaManager - https://digitalnewtamanager.vercel.app/", { align: "center" });

    doc.end();
  });
};

// Generate CSV string
const generateCSV = (guests) => {
  const headers = "S.No,Name,Village,Mobile,Tag,Priority,Attended,Amount,Payment Type,Added On";
  const rows = guests.map((g, i) =>
    `${i + 1},"${g.name}","${g.village}",${g.mobileNumber || "N/A"},${g.tag || "—"},${g.priority || "—"},${g.attended ? "Yes" : "No"},${g.amount || 0},${g.paymentType || "—"},${g.addedOn || "—"}`
  );
  return [headers, ...rows].join("\n");
};

// Generate text content
const generateText = (wedding, guests, stats) => {
  const divider = "═".repeat(100);
  let text = `Digital Newta Manager - Wedding Summary\n${divider}\n`;
  text += `${wedding.brideName} & ${wedding.groomName}\n`;
  text += `Date: ${new Date(wedding.date).toLocaleDateString("en-IN")}  |  Venue: ${wedding.venue}\n`;
  text += `${divider}\n`;
  text += `Total Guests: ${guests.length} | Attended: ${stats.attended} | Total Amount: ₹${stats.totalAmount.toLocaleString()}\n`;
  text += `Cash: ${stats.cashCount} | UPI: ${stats.upiCount} | Envelope: ${stats.envelopeCount}\n`;
  text += `${divider}\n\n`;

  const header = `#   Name                 | Village        | Mobile       | Tag        | Pri | Att | Amount  | Payment  | Added`;
  text += `${header}\n${"─".repeat(100)}\n`;

  guests.forEach((g, i) => {
    text += `${String(i + 1).padEnd(4)}${g.name.padEnd(20)} | ${g.village.padEnd(14)} | ${(g.mobileNumber || "N/A").padEnd(12)} | ${(g.tag || "—").padEnd(10)} | ${String(g.priority || "—").padEnd(3)} | ${g.attended ? "Yes" : "No "} | ₹${String(g.amount || 0).padEnd(6)} | ${(g.paymentType || "—").padEnd(8)} | ${g.addedOn || "—"}\n`;
  });

  return text;
};

// Send the post-wedding summary email
export const sendPostWeddingSummary = async (userEmail, userName, wedding, guests) => {
  const stats = {
    attended: guests.filter((g) => g.attended).length,
    totalAmount: guests.reduce((sum, g) => sum + (g.amount || 0), 0),
    cashCount: guests.filter((g) => g.paymentType === "cash").length,
    upiCount: guests.filter((g) => g.paymentType === "upi").length,
    envelopeCount: guests.filter((g) => g.paymentType === "envelope").length,
  };

  const activeGuests = guests.filter((g) => !g.isDeleted);
  const pdfBuffer = await generatePDF(wedding, activeGuests, stats);
  const csvContent = generateCSV(activeGuests);
  const textContent = generateText(wedding, activeGuests, stats);

  const fileName = `${wedding.brideName}-${wedding.groomName}-summary`;

  const mailOptions = {
    from: process.env.EMAIL_USER,
    to: userEmail,
    subject: `🎉 Congratulations! ${wedding.brideName} & ${wedding.groomName}'s Wedding Summary`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <h1 style="color: #C41E3A; text-align: center;">💍 Congratulations! 💍</h1>
        <p style="font-size: 16px; text-align: center;">Dear <strong>${userName}</strong>,</p>
        <p style="font-size: 14px; text-align: center; color: #555;">
          The wedding of <strong>${wedding.brideName}</strong> & <strong>${wedding.groomName}</strong> has been beautifully completed! 🎊
        </p>
        <div style="background: #FFF0F5; border-radius: 10px; padding: 15px; margin: 15px 0; text-align: center;">
          <h3 style="color: #8B008B; margin: 0 0 10px;">📊 Quick Summary</h3>
          <p style="margin: 5px 0;">👥 Total Guests: <strong>${activeGuests.length}</strong></p>
          <p style="margin: 5px 0;">🎉 Attended: <strong>${stats.attended}</strong></p>
          <p style="margin: 5px 0;">💰 Total Collection: <strong>₹${stats.totalAmount.toLocaleString()}</strong></p>
          <p style="margin: 5px 0;">💵 Cash: ${stats.cashCount} | 🔗 UPI: ${stats.upiCount} | ✉️ Envelope: ${stats.envelopeCount}</p>
        </div>
        <p style="font-size: 13px; color: #777; text-align: center;">
          Your complete guest data is attached in PDF, CSV, and Text formats.<br/>
          May this new journey bring endless happiness! 🌸
        </p>
        <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
        <p style="font-size: 11px; color: #999; text-align: center;">
          — DigitalNewtaManager | <a href="https://digitalnewtamanager.vercel.app/">Visit Website</a>
        </p>
      </div>
    `,
    attachments: [
      { filename: `${fileName}.pdf`, content: pdfBuffer, contentType: "application/pdf" },
      { filename: `${fileName}.csv`, content: csvContent, contentType: "text/csv" },
      { filename: `${fileName}.txt`, content: textContent, contentType: "text/plain" },
    ],
  };

  return transporter.sendMail(mailOptions);
};
